FROM liquibase/liquibase

COPY ./migrations /liquibase/changelog
WORKDIR /liquibase/changelog

CMD ["sh", "-c", "liquibase \
  --changeLogFile=changelog.xml \
  --url=jdbc:postgresql://$DB_HOST:$DB_PORT/$DB_DB \
  --username=$DB_USER \
  --password=$DB_PASSWORD update && \
  tail -f /dev/null"]
