CREATE_CHAT = "🆕 Create chat"
OPEN_CHAT = "open_chat_"
DELETE_CHAT = "🗑️ Delete Chat"
CANCEL = "❌ Cancel"
BACK_TO_MENU = "🏠 Main Menu"

FILL_PLAN = "📝 Create a personal plan"
GET_RECOMMENDATIONS = "💡 Get Recommendations"
UPDATE_RECOMMENDATIONS = "🔄 Update Recommendations"
SKIP_STEP = "⏭️ Skip"
